#!/bin/sh
# Network Status Monitor - notify NFS peers of reboots. For NFS v2 and v3 only.
# Activated automatically from rpcbind
# (cloux@rote.ch)
exec 2>&1

NAME=rpc.statd
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# Load config
[ -r /etc/default/nfs-common ] && . /etc/default/nfs-common

# Terminate unsupervised instance
pkill --exact "$NAME" 2>/dev/null

exec "$DAEMON" --foreground $STATDOPTS
