#!/bin/sh
# Redis Server - in memory key-value database, cache and message broker
#
# (cloux@rote.ch)
exec 2>&1

# only run finish if run exited normally
[ "$1" = "0" ] || exit

NAME=${PWD##*/}
[ -d /etc/redis/${NAME}.post-down.d ] && \
  su redis -s /bin/sh -c "run-parts --exit-on-error /etc/redis/${NAME}.post-down.d"
