#!/bin/sh
exec 2>&1

LOGFILE=/var/log/boot.log
[ -r ./config ] && . ./config

NAME=bootlogd
DAEMON=$(command -v "$NAME")
[ -x "$DAEMON" ] || exit 0

# stop any bootlog daemons running outside of runsvdir
killall --quiet --exact "$NAME"

exec $DAEMON -d -c -l "$LOGFILE"
