#!/bin/sh
# 
# AWS EC2 cloud-init, see /etc/init.d/cloud-init
# This is started parallel in the background (nohup) by 20-parallel.sh
# (cloux@rote.ch)

# clean up
rm -f /var/log/cloud-init.log /var/log/cloud-init-output.log
[ -d /var/lib/cloud/instance ] && rm -rf /var/lib/cloud/instance
# load config
[ -r /etc/default/cloud-init ] && . /etc/default/cloud-init
# discard output
exec >/dev/null
exec 2>/dev/null
# init
/usr/bin/cloud-init init
/usr/bin/cloud-init init --local
/usr/bin/cloud-init modules --mode config
/usr/bin/cloud-init modules --mode final
