#!/bin/sh
exec 2>&1
NAME=rsyslog
DAEMON=/usr/sbin/rsyslogd

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

exec $DAEMON
