#!/bin/sh
# PHP-FPM: PHP FastCGI Process Manager
#
# (cloux@rote.ch)
exec 2>&1

DAEMON="$(command -v php-fpm)"
[ -x "$DAEMON" ] || exit 0

FPM_CONF=/etc/php-fpm.conf
[ -f "$FPM_CONF" ] || exit 0

# get php.ini
PHP_INI=$($DAEMON -i 2>/dev/null | grep -o '[^> ]*/php.ini' | tail -n 1)
# if FPM php.ini is not available, use php.ini from php-cgi
[ -f "$PHP_INI" ] || PHP_INI=$(php-cgi -i 2>/dev/null | grep -o '[^> ]*/php.ini' | tail -n 1)
[ -f "$PHP_INI" ] || exit 0

exec $DAEMON --nodaemonize --fpm-config "$FPM_CONF" --php-ini "$PHP_INI"
