#!/bin/sh
exec 2>&1

DAEMON=$(command -v sshd)
[ -x "$DAEMON" ] || exit

# ensure sysvinit compatibility - replace init.d script with symlink to sv
NAME=${PWD##*/}
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

# generate host keys if they don't already exist
ssh-keygen -A >/dev/null

[ -r /etc/default/ssh ] && . /etc/default/ssh
[ -r ./conf ] && . ./conf

# Create the PrivSep empty dir if necessary
if [ ! -d /var/run/sshd ]; then
  rm -f /var/run/sshd; mkdir -p /var/run/sshd; chmod 0755 /var/run/sshd
fi

exec $DAEMON $SSHD_OPTS
