#!/bin/sh
#
# Runit stage 1: one time bootup system tasks
# based on VOID Linux (https://www.voidlinux.eu)

PATH=/usr/sbin:/usr/bin:/sbin:/bin

# copy /dev/console messages to a logfile
[ -x /sbin/bootlogd ] && /sbin/bootlogd -c -l /var/log/boot.log

. /etc/runit/functions

msg "Welcome to Devuan!"
msg "Entering Runit stage 1 ($0)"

[ -r /etc/rc.conf ] && . /etc/rc.conf
detect_virt

# rcS tasks are handled by runit 'bootup' scripts
#/etc/init.d/rcS

# Run bootup scripts: one-time system tasks
for f in /etc/runit/bootup/*.sh; do
  [ -r $f ] && . $f
done

dmesg >/var/log/dmesg.log
if [ $(sysctl -n kernel.dmesg_restrict 2>/dev/null) -eq 1 ]; then
  chmod 0600 /var/log/dmesg.log
else
  chmod 0644 /var/log/dmesg.log
fi

# set soft reboot as the default operation
install --mode=0 /dev/null /run/runit.stopit
install --mode=755 /dev/null /run/runit.reboot
install --mode=755 /dev/null /run/runit.kexecreboot

#[ -e /etc/runit/no-emulate-sysv ] || /etc/init.d/rc 5

msg "Runit stage 1 complete, running stage 2..."
