#!/bin/sh
#
# Runit stage 1: one time bootup system tasks
# based on VOID Linux (https://www.voidlinux.org)

PATH=/usr/sbin:/usr/bin:/sbin:/bin

BOOTSTART=$(date +%s.%N)

# copy /dev/console messages to a logfile
if [ -e /etc/service/bootlogd ] && [ -x /sbin/bootlogd ]; then
	mountpoint -q /dev || mount -o mode=0755,nosuid -t devtmpfs dev /dev
	[ -d /dev/pts ] || mkdir -m0755 /dev/pts
	mountpoint -q /dev/pts || mount -o mode=0620,gid=5,nosuid,noexec -n -t devpts devpts /dev/pts
	/sbin/bootlogd -c -l /var/log/boot.log
fi

. /etc/runit/functions

msg "Welcome to Devuan!"
msg "Entering Runit stage 1 ($0)"

[ -r /etc/rc.conf ] && . /etc/rc.conf
detect_virt

# Run bootup scripts
for f in /etc/runit/bootup/*.sh; do
	[ -r "$f" ] && . "$f"
done

dmesg >/var/log/dmesg.log
if [ $(sysctl -n kernel.dmesg_restrict 2>/dev/null) -eq 1 ]; then
	chmod 0600 /var/log/dmesg.log
else
	chmod 0644 /var/log/dmesg.log
fi

BOOTTIME=$(printf "scale=3; (%s - %s)/1\n" $(date +%s.%N) $BOOTSTART | bc)
msg "Runit stage 1 completed in $BOOTTIME sec, running stage 2..."
