#!/bin/sh
#
# Runit stage 3: halt or restart system
# based on VOID Linux (https://www.voidlinux.org)
exec 2>&1

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 

. /etc/runit/functions

msg "Entering Runit stage 3 ($0)"

detect_virt
[ -r /etc/rc.conf ] && . /etc/rc.conf

if [ -e /run/runit.kexecreboot ]; then
	if command -v kexec >/dev/null; then
		msg "Rebooting using kexec"
	else
		msg_error "kexec reboot failed, rebooting normally"
	fi
elif [ -e /run/runit.reboot ]; then
	msg "Rebooting system"
else
	msg "Shutdown and halt the system"
fi

msg "Waiting for services to stop..."
msg "Further messages will not be logged to disk"
sv -w 5 force-stop /etc/service/*
sv exit /etc/service/*

# rotate boot.log file
mv -f /var/log/boot.log /var/log/boot.log.1

[ -x /etc/rc.shutdown ] && /etc/rc.shutdown

msg "Saving random seed..."
( umask 077; bytes=$(cat /proc/sys/kernel/random/poolsize) || bytes=512; \
  dd if=/dev/urandom of=/var/lib/random-seed count=1 bs=$bytes >/dev/null 2>&1 )

if [ -z "$VIRTUALIZATION" ]; then
	msg "Stopping udev..."
	udevadm control --exit
fi

msg "Sending ALRM signal to processes..."
kill -14 -1
msg "Sending TERM signal to processes..."
pkill --inverse --session 0,1 -TERM
sleep 1
msg "Sending KILL signal to processes..."
pkill --inverse --session 0,1 -KILL

if [ -z "$VIRTUALIZATION" ]; then
	msg "Unmounting filesystems, disabling swap..."
	swapoff -a
	umount -r -a -t noproc,nosysfs,nodevfs,nodevpts,nodevtmpfs,notmpfs &
	sleep 0.5
fi

if [ -z "$VIRTUALIZATION" ]; then
	deactivate_vgs
	if [ -e /run/runit.kexecreboot ] && command -v kexec >/dev/null; then
		msg "Triggering kexec reboot of the current kernel..."
		kexec -e 2>/dev/null
		# not reached when kexec was successful.
	fi
fi

msg "Triggering reboot..."
