#!/bin/sh
#
# Activate runit core, replace default sysvinit commands
# (cloux@rote.ch)
exec 2>/dev/null

if [ ! -f /sbin/svactivate ]; then
	printf "Link sv commands ...\n"
	ln -sf /etc/runit/svactivate /sbin/
	ln -sf /etc/runit/svdeactivate /sbin/
fi

# remove unnecessary runscripts from getty-run package
if [ -d /etc/sv/getty-tty1 ]; then
	printf "Remove default getty-tty runscripts ...\n"
	svdeactivate /etc/service/getty-tty* >/dev/null
	rm -rf /etc/sv/getty-tty*
fi

# move socklog commands away from /command
if [ -d /command ]; then
	printf "Move socklog commands from /command/* into /usr/local/bin\n"
	for cmdlink in $(find /command -type l 2>/dev/null); do
		cp --dereference --remove-destination "$cmdlink" /usr/local/bin/
		[ $? -eq 0 ] && rm "$cmdlink" 2>/dev/null
	done
	rmdir /command 2>/dev/null
fi
