#!/bin/sh
#
# Activate runit core, replace default sysvinit commands
# (cloux@rote.ch)

if [ "$(readlink /sbin/shutdown)" != "/etc/runit/shutdown" ]; then
	mv -f /sbin/shutdown /sbin/shutdown.dpkg
	ln -s /etc/runit/shutdown /sbin/shutdown
fi

if [ "$(readlink /sbin/halt)" != "/etc/runit/shutdown" ]; then
	mv -f /sbin/halt /sbin/halt.dpkg
	ln -s /etc/runit/shutdown /sbin/halt
fi

if [ "$(readlink /sbin/reboot)" != "/etc/runit/ctrlaltdel" ]; then
	mv -f /sbin/reboot /sbin/reboot.dpkg
	ln -s /etc/runit/ctrlaltdel /sbin/reboot
fi

if [ ! -f /sbin/svactivate ]; then
	printf "Link sv commands ...\n"
	ln -sf /etc/runit/svactivate /sbin/
	ln -sf /etc/runit/svdeactivate /sbin/
fi

# move socklog commands into usual paths
if [ -d /command ]; then
	printf "Move socklog commands from /command/* into usual paths\n"
	for cmdlink in $(find /command -type l 2>/dev/null); do
		cp --dereference --remove-destination "$cmdlink" /usr/local/bin/
		[ $? -eq 0 ] && rm "$cmdlink" 2>/dev/null
	done
	rmdir /command 2>/dev/null
fi
