#!/bin/sh

PATH=/usr/sbin:/usr/bin:/sbin:/bin

[ -x /sbin/runit-init ] || exit

# We check for this file in stage3 to halt or reboot
install --mode=755 /dev/null /run/runit.stopit
rm -f /run/runit.reboot /run/runit.kexecreboot

# Proceed with shutdown process
printf "\nSystem is going down...\n" | wall --nobanner

/sbin/runit-init 0

# Don't give the terminal back immediately, the user should not be doing
# anything more, just wait for the reboot. If after 15 seconds
# the machine still is not rebooted, probably something went wrong, then
# give the terminal back. Ctrl+C gives the terminal back immediately.
sleep 15
