#!/bin/bash
#
# runit service activation
# (cloux@rote.ch)

if [ $# -eq 0 ]; then
	echo "Enter Runit service names as a parameter."
	echo "Supported services are listed in /etc/sv/"
	exit 0
fi

# process all services provided as command line parameters
RET=0
for SRV in ${@}; do
	SRVNAME=${SRV##*/}
	if [ -d "/etc/service/$SRVNAME" ]; then
		echo "Info: Runit service '$SRVNAME' is already active"
		continue
	fi
	if [ ! -d "/etc/sv/$SRVNAME" ]; then
		echo "ERROR: Runit service definition '/etc/sv/$SRVNAME' not found, activation failed"
		RET=1
		continue
	fi
	ln -s "/etc/sv/$SRVNAME" /etc/service/ 2>/dev/null
	if [ $? -ne 0 ]; then
		echo "ERROR: Runit service '$SRVNAME' activation failed"
		RET=1
	fi
done

exit $RET
