#!/bin/bash
#
# runit service activation
# (cloux@rote.ch)

if [ $# -eq 0 ]; then
	echo "Enter Runit service name as a parameter."
	echo "Supported services are listed in /etc/sv/"
	exit 0
fi

# process all services provided as command line parameters
RET=0
for SRV in ${@}; do
	if [ -d "/etc/service/$SRV" ]; then
		echo "Info: Runit service '$SRV' is already active"
		continue
	fi
	if [ ! -d "/etc/sv/$SRV" ]; then
		echo "ERROR: Runit service definition '/etc/sv/$SRV' not found, activation failed"
		RET=1
		continue
	fi
	ln -s "/etc/sv/$SRV" /etc/service/ 2>/dev/null
	if [ $? -ne 0 ]; then
		echo "ERROR: Runit service $SRV activation failed"
		RET=1
	fi
done

exit $RET
