#!/bin/bash
#
# runit service deactivation
# (cloux@rote.ch)

if [ $# -eq 0 ]; then
	echo "Enter Runit service names as a parameter."
	echo "Supervised services are listed in /etc/service/"
	exit 0
fi

# process all services provided as command line parameters
RET=0
for SRV in ${@}; do
	SRVNAME=${SRV##*/}
	if [ ! -d "/etc/service/$SRVNAME" ]; then
		if [ -d "/etc/sv/$SRVNAME" ]; then
			echo "Info: Runit service '$SRVNAME' is already inactive"
		else
			echo "Warning: Runit service definition '/etc/sv/$SRVNAME' doesn't exist and cannot be activated or deactivated"
		fi
		continue
	fi
	rm "/etc/service/$SRVNAME" 2>/dev/null
	if [ $? -ne 0 ]; then
		echo "ERROR: Runit service '$SRVNAME' deactivation failed"
		RET=1
	fi
done

exit $RET
