#!/bin/sh
# Monitor system downtime
# NOTE: default logging facility is syslog: deamon
#
# (cloux@rote.ch)
exec 2>&1

NAME=${PWD##*/}
DAEMON=$(command -v "$NAME")
[ -x "$DAEMON" ] || exit

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

[ -r ./conf ] && . ./conf
[ "$FSYNC" = "n" ] && PAR_DISABLE_FSYNC="-S"
(printf "%s" "$RESOLUTION" | grep -q '^[0-9]*$') && PAR_SPEED="-s $RESOLUTION"

exec "$DAEMON" -F -p none $PAR_DISABLE_FSYNC $PAR_SPEED
