#!/bin/sh
exec 2>&1

# Get service name (the upper directory name)
UPDIR=$(dirname $PWD)
SERVICE=${UPDIR##*/}
LOGDIR=/var/log/$SERVICE
BUFFER=2048
LOGUSER=daemon

# Read configuration file
[ -r ./conf ] && . ./conf

[ -f "$LOGDIR" ] && rm -f "$LOGDIR"
[ ! -d "$LOGDIR" ] && mkdir -p "$LOGDIR"

# manage log config file
# see https://gitlab.com/flussence/runit-scripts/blob/master/svlogd.run.sh
if [ -f "$UPDIR"/log.config ]; then
  install -Tm 0644 "$UPDIR"/log.config "$LOGDIR"/config
elif [ -f "$PWD"/log.config ]; then
  install -Tm 0644 "$PWD"/log.config "$LOGDIR"/config
fi

chown -R ${LOGUSER}: "$LOGDIR"
exec chpst -u${LOGUSER} svlogd -tt -b $BUFFER "$LOGDIR"
