#!/bin/sh
# Redis Sentinel - high availability and monitor for Redis Server
#
# (cloux@rote.ch)
exec 2>&1

NAME=redis-sentinel
CONFIG=/etc/redis/sentinel.conf
DAEMON="$(command -v $NAME)"
[ -x "$DAEMON" ] || exit 1

[ -d /etc/redis/${NAME}.pre-up.d ] && \
  su redis -s /bin/sh -c "run-parts --exit-on-error /etc/redis/${NAME}.pre-up.d"

# disable daemonization in the config file
[ -f "$CONFIG" ] && sed -i 's/^\s*daemonize\s*y.*/daemonize no/g' $CONFIG

# end all other unsupervised processes
killall --quiet --exact "$NAME"
[ "$(pgrep $NAME)" ] && exit

exec chpst -u redis $DAEMON $CONFIG
