#!/bin/sh -e
#
# remove old files from apt cache
MAXDAYS=3

# run only if can be started nicely
[ -x "$(which ionice 2>/dev/null)" ] || exit 1

ionice --class 3 --ignore /usr/bin/find /var/cache/apt/archives -type f -ctime +${MAXDAYS} -delete >/dev/null 2>/dev/null
