#!/bin/sh -e

# load config files
[ -r /etc/default/auditd ] && . /etc/default/auditd
[ -r conf ] && . ./conf

if [ "${AUDITD_CLEAN_STOP,,}" != "no" ]; then
  [ -f /etc/audit/audit-stop.rules ] && /sbin/auditctl -R /etc/audit/audit-stop.rules 2>/dev/null >/dev/null
fi
