#!/bin/sh
exec 2>&1

# load config files
[ -r /etc/default/auditd ] && . /etc/default/auditd
[ -r ./conf ] && . ./conf

if [ -z "$(printf "%s" "$USE_AUGENRULES" | grep -i 'no')" ]; then
  [ -d /etc/audit/rules.d ] && /sbin/augenrules >/dev/null
fi
[ -f /etc/audit/audit.rules ] && /sbin/auditctl -R /etc/audit/audit.rules 2>/dev/null >/dev/null

exec /sbin/auditd -f -n $EXTRAOPTIONS
