#!/bin/sh -e
exec 2>&1

# load config files
[ -r /etc/default/auditd ] && . /etc/default/auditd
[ -r conf ] && . ./conf

if [ "${USE_AUGENRULES,,}" != "no" ]; then
  [ -d /etc/audit/rules.d ] && /sbin/augenrules >/dev/null
fi
[ -f /etc/audit/audit.rules ] && /sbin/auditctl -R /etc/audit/audit.rules 2>/dev/null >/dev/null

exec /sbin/auditd -f -n $EXTRAOPTIONS
