#!/bin/sh
#
# Monit utility for monitoring services on a Unix system
#
# Default config file: ~/.monitrc, /etc/monitrc
# To check for syntax errors, run: monit -t
exec 2>&1

NAME=monit
DAEMON=$(command -v "$NAME")
[ -x "$DAEMON" ] || exit 0

# kill all monit background daemons, if any
"$DAEMON" quit >/dev/null 2>/dev/null

exec "$DAEMON" -I
