#!/bin/sh -e
exec 2>&1

DAEMON=/usr/sbin/uuidd
UUIDD_USER=uuidd
UUIDD_GROUP=uuidd
UUIDD_DIR=/run/uuidd

[ -x "$DAEMON" ] || exit 0
[ -r ./conf ] && . ./conf

if [ ! -d $UUIDD_DIR ]; then
	install --group="$UUIDD_GROUP" --owner="$UUIDD_USER" -d "$UUIDD_DIR"
fi

exec $DAEMON --no-fork --no-pid --quiet
