#!/bin/sh
# RPCSEC_GSS daemon - provide strong security for NFS
# Activated automatically from rpcbind
# (cloux@rote.ch)
exec 2>&1

DAEMON=$(command -v rpc.gssd)
[ -x "$DAEMON" ] || exit

KEYTAB=/etc/krb5.keytab
[ -f ./conf ] && . ./conf

# Ensure that the RPC pipefs is available
if ! (mount | grep -q '^rpc_pipefs'); then
	printf "ERROR: rpc.gssd requires rpc_pipefs to be mounted.\n"
	exit 1
fi

exec "$DAEMON" -f -k "$KEYTAB"
