#!/bin/sh
# MongoDB server
exec 2>&1

DAEMON="$(which mongod)"
[ -x "$DAEMON" ] || exit 0

OPTIONS=
[ -r ./config ] && . ./config
[ -f /etc/mongodb.conf ] && OPTIONS+="--config /etc/mongodb.conf"

exec chpst -u mongodb $DAEMON $OPTIONS
