#!/bin/sh
# (cloux@rote.ch)
exec 2>&1

NAME=dovecot
DAEMON=$(command -v "$NAME")
[ -x "$DAEMON" ] || exit

# Service instancing; name the runsv dir "dovecot" if unsure
dovecot_config_file=/etc/dovecot/"${PWD##*/}".conf
[ -f "$dovecot_config_file" ] || exit

# N.B. Dovecot legitimately uses this dir for state, not just dumping a pidfile into:
install -m 0755 -d "$(/usr/bin/doveconf -h base_dir -c "$dovecot_config_file")"

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

exec "$DAEMON" -F -c "$dovecot_config_file"
