#!/bin/sh
# Raise network interfaces.
exec 2>&1

RUN_DIR="/run/network"
IFSTATE="$RUN_DIR/ifstate"
STATEDIR="$RUN_DIR/state"

[ -x /sbin/ifup ] || exit 0
[ -x /sbin/ifdown ] || exit 0

CONFIGURE_INTERFACES=yes
EXCLUDE_INTERFACES=
VERBOSE=no

[ -f /etc/default/networking ] && . /etc/default/networking

verbose=""
[ "$VERBOSE" = yes ] && verbose=-v

if [ ! -d "$RUN_DIR" ] ; then
  if ! mkdir -p "$RUN_DIR" ; then
    echo "can't create $RUN_DIR"
    exit 1
  fi
  if ! chown root:netdev "$RUN_DIR" ; then
    echo "can't chown $RUN_DIR"
  fi
fi
if [ ! -r "$IFSTATE" ] ; then
  if ! :> "$IFSTATE" ; then
    echo "can't initialise $IFSTATE"
    exit 1
  fi
fi

if [ "$CONFIGURE_INTERFACES" = no ]; then
  echo "Not configuring network interfaces, see /etc/default/networking"
  exit 0
fi

ifup_hotplug () {
  if [ -d /sys/class/net ]
  then
    ifaces=$(for iface in $(ifquery --list --allow=hotplug)
            do
                    link=${iface##:*}
                    link=${link##.*}
                    if [ -e "/sys/class/net/$link" ]
                    then
                        echo "$iface"
                    fi
            done)
    if [ -n "$ifaces" ]
    then
      ifup $ifaces "$@" || true
    fi
  fi
}

if [ -x /sbin/udevadm ]; then
  if [ -n "$(ifquery --list --exclude=lo)" ] || [ -n "$(ifquery --list --allow=hotplug)" ]; then
    udevadm settle || true
  fi
fi

ifup -a $verbose
ifup_hotplug $verbose

