#!/bin/sh

OPENVPN=/usr/sbin/openvpn
OPENVPN_INIT=/etc/init.d/openvpn
SYSTEMCTL=/bin/systemctl
SYSTEMD=/run/systemd/system

[ -x $OPENVPN ] || exit 0

if [ -n "$IF_OPENVPN" ]; then
	for vpn in $IF_OPENVPN; do
		if [ "$(pgrep runsvdir)" ]; then
			# runit supervisor
			sv down /etc/service/openvpn* >/dev/null || true
		elif [ -d $SYSTEMD ]; then
			# systemd
			$SYSTEMCTL stop openvpn@$vpn
		else
			# sysvinit
			$OPENVPN_INIT stop $vpn
		fi
	done
fi
