#!/bin/sh
# Samba server
# (cloux@rote.ch)
exec 2>&1

NAME=${PWD##*/}
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

CONFIG_FILE=/etc/samba/smb.conf
[ -r ./conf ] && . ./conf
[ -e "$CONFIG_FILE" ] && CONF_PARAM="--configfile=$CONFIG_FILE"

exec "$DAEMON" --foreground --log-stdout $CONF_PARAM 2>&1
