#!/bin/sh
# Udevil Devmon - Automounts and unmounts optical and removable drives
# (cloux@rote.ch)
exec 2>&1

DAEMON=$(command -v devmon)
[ -x "$DAEMON" ] || exit

CONF_PARAM=""
[ -r ./conf ] && . ./conf

exec chpst -u daemon:daemon "$DAEMON" --info-on-mount $CONF_PARAM
