#!/bin/sh
# The inotify cron daemon (incrond) monitors filesystem events
# and executes commands defined in system and user tables.
# (cloux@rote.ch)
exec 2>&1

NAME=incrond
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

INCROND_CONF=/etc/incron.conf

# WARNING:
# If incrond can't connect to syslog service by openlog() call
# it will keep polluting /dev/console.
sv start socklog-unix >/dev/null

exec "$DAEMON" --foreground -f "$INCROND_CONF"
