#!/bin/sh
# The inotify cron daemon (incrond) monitors filesystem events
# and executes commands defined in system and user tables.
# (cloux@rote.ch)
exec 2>&1

DAEMON=$(command -v incrond)
[ -x "$DAEMON" ] || exit

# ensure sysvinit compatibility - replace init.d script with symlink to sv
NAME=${PWD##*/}
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

# WARNING:
# If incrond can't connect to syslog service by openlog() call
# it will keep polluting /dev/console.
sv start socklog >/dev/null || sleep 1
socklog-check 2>/dev/null || sleep 1

exec "$DAEMON" --foreground -f /etc/incron.conf >/dev/null 2>/dev/null
