#!/bin/sh
# NFS common client and server universal addresses to RPC program number mapper
# Equivalent of /etc/init.d/nfs-common
# (cloux@rote.ch)
exec 2>&1

NAME=rpcbind
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# Load config defaults
[ -r /etc/default/nfs-common ] && . /etc/default/nfs-common
# Autodetect missing settings
[ -z "$NEED_GSSD" ] && grep -v '^\s*#' /etc/fstab | sed 's/\s\s*/\t/g' | \
                       cut -s -f 4 | grep -q 'sec=krb5' && NEED_GSSD=yes
[ -z "$NEED_STATD" ] && NEED_STATD=yes
# Allow local conf override
[ -r ./conf ] && . ./conf

# Activate/deactivate additional NFS support services as needed:
#
# GSSD is required for Kerberos mounts
if [ "$NEED_GSSD" = "yes" ] && [ -x "$(command -v rpc.gssd)" ]; then
	svactivate rpc.gssd >/dev/null
else
	svdeactivate rpc.gssd >/dev/null
fi
# STATD is only needed for NFSv2 and NFSv3
if [ "$NEED_STATD" = "yes" ] && [ -x "$(command -v rpc.statd)" ]; then
	svactivate rpc.statd >/dev/null
else
	svdeactivate rpc.statd >/dev/null
fi
# IDMAPD is only needed for NFSv4 server. On more recent kernels,
# the client uses nfsidmap instead, and only falls back to rpc.idmapd
# if there was a problem running the nfsidmap program.
if [ "$NEED_IDMAPD" = "no" ]; then
	svdeactivate rpc.idmapd >/dev/null
elif ([ "$NEED_IDMAPD" = "yes" ] || ! nfsidmap -d >/dev/null 2>/dev/null) && \
      [ -x "$(command -v rpc.idmapd)" ]; then
	svactivate rpc.idmapd >/dev/null
else
	# make sure service goes up again, if activated by rpc.mountd
	sv up rpc.idmapd >/dev/null
fi

# Terminate unsupervised instance
killall --quiet --exact "$NAME"

# Run rpcbind daemon
exec "$DAEMON" -wf
