#!/bin/sh
# Stop additional nfs-kernel-server services
# (cloux@rote.ch)
exec 2>&1

sv down rpc.svcgssd >/dev/null
sv down rpc.nfsd

# Unexporting directories for NFS
exportfs -au 2>/dev/null
exportfs -f 2>/dev/null
