#!/bin/sh
# NFS mount daemon - implements the server side of the NFS MOUNT protocol
# Equivalent of /etc/init.d/nfs-kernel-server.
# (cloux@rote.ch)
exec 2>&1

NAME=rpc.mountd
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit
EXPORTFS=$(command -v exportfs)
[ -x "$EXPORTFS" ] || exit
sv start rpcbind || exit

# See if our running kernel supports NFSD
if ! grep -qs '\snfsd$' /proc/filesystems; then
	printf "No NFSD support in current kernel.\n"
	exit
fi

# Load config
[ -r /etc/default/nfs-common ] && . /etc/default/nfs-common
[ -r /etc/default/nfs-kernel-server ] && . /etc/default/nfs-kernel-server
[ -z "$NEED_SVCGSSD" ] && NEED_SVCGSSD=yes
[ -r ./conf ] && . ./conf

# Synchronize /var/lib/nfs/etab with /etc/exports and /etc/exports.d
"$EXPORTFS" -r

# Activate support services
[ mountpoint -q "/proc/fs/nfsd" ] || mount -t nfsd nfsd /proc/fs/nfsd
svactivate rpc.nfsd >/dev/null
# SVCGSSD is only required for Kerberos exports
[ "$NEED_SVCGSSD" = "yes" ] && [ -x "$(command -v rpc.svcgssd)" ]  && svactivate rpc.svcgssd
# IDMAPD might not be activated from rpcbind as common service, but is required for the server
([ "$NEED_IDMAPD" != "no" ] && [ -x "$(command -v rpc.idmapd)" ]) && svactivate rpc.idmapd >/dev/null

# Terminate unsupervised instance
pkill --exact "$NAME" 2>/dev/null

# Run mountd
exec "$DAEMON" --foreground $RPCMOUNTDOPTS
