#!/bin/sh
# NFS server process - user level part of the NFS service
# Activated automatically from rpc.mountd
# (cloux@rote.ch)
exec 2>&1

NAME=rpc.nfsd
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# Make sure the rpc.mountd daemon is activated
svactivate rpc.mountd >/dev/null

# Load config
RPCNFSDCOUNT="$(nproc)"
RPCNFSDPRIORITY=0
[ -r /etc/default/nfs-kernel-server ] && . /etc/default/nfs-kernel-server
# Allow local config override
[ -r ./conf ] && . ./conf

# Terminate other instances
killall --quiet --exact "$NAME"

# Run nfsd kernel service. Doesn't have a foreground mode.
nice -n $RPCNFSDPRIORITY "$DAEMON" -- $RPCNFSDCOUNT
exec chpst -L supervise/runlock chpst -l supervise/runlock true
