#!/bin/sh
exec 2>&1

([ -x /sbin/udevd ] && [ -x /sbin/udevadm ]) || exit

# udevd could be started unsupervised in the early init.
# kill the old daemon first
/sbin/udevadm control --exit

exec /sbin/udevd
