#!/bin/sh
# Server-side RPCSEC_GSS daemon - provide strong security for NFS
# Activated automatically from rpc.mountd
# (cloux@rote.ch)
exec 2>&1

NAME=rpc.svcgssd
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# Terminate unsupervised instance
killall --quiet --exact "$NAME"

exec "$DAEMON" -f
