#!/bin/sh
# Bluetooth daemon
# (cloux@rote.ch)
exec 2>&1

DAEMON=$(command -v bluetoothd)
[ -x "$DAEMON" ] || exit

# Start DBus
sv up dbus >/dev/null

# Configuration
NOPLUGIN_OPTION=""
[ -f /etc/default/bluetooth ] && . /etc/default/bluetooth
[ -r ./conf ] && . ./conf

# ensure sysvinit compatibility - replace init.d script with symlink to sv
NAME=${PWD##*/}
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

exec "$DAEMON" --nodetach $NOPLUGIN_OPTION
