#!/bin/sh
#
# integrate socket loging into /var/log/ directory
# (cloux@rote.ch)

LOGDIR=/var/log
LOGUSER=daemon
SOCKLOG_SERVICES=""

[ -r ../config ] && . ../config
[ -r config ] && . config

LOGGED=""
for SRV in $SOCKLOG_SERVICES; do
  if [ -d "../templates/$SRV" ] && [ ! -d "$LOGDIR/$SRV" ]; then
    cp -Pr "../templates/$SRV" "$LOGDIR/$SRV" 2>/dev/null
    chown -R "$LOGUSER": "$LOGDIR/$SRV" 2>/dev/null
  fi
  if [ -f "$LOGDIR/$SRV/config" ]; then
    [ "$LOGGED" ] && LOGGED="$LOGGED "
    LOGGED="$LOGGED""$LOGDIR/$SRV"
  fi
done

[ "$LOGGED" ] || exit 1

exec chpst -u$LOGUSER svlogd $LOGGED
