#!/bin/sh
# daemon to balance interrupts for SMP systems
exec 2>&1

NAME=${PWD##*/}
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# On single-CPU systems, irqbalabce has no effect and exits immediately.
# Supervise it only on multi-CPU systems!
if [ "$(nproc --all 2>/dev/null)" -eq 1 ]; then
	sv exit $NAME
	exit
fi

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

exec "$DAEMON" --foreground
