#!/bin/sh
# daemon to balance interrupts for SMP systems
# NOTE: on single-CPU systems, irqbalabce has no effect and exits immediately
exec 2>&1

NAME=irqbalance
DAEMON=/usr/sbin/$NAME

# Defaults - don't touch, edit /etc/default/irqbalance
OPTIONS=""
ONESHOT=0

[ -x $DAEMON ] || exit 0

[ -f /etc/default/$NAME ] && . /etc/default/$NAME

exec $DAEMON --foreground $OPTIONS
