#!/bin/sh
# daemon to balance interrupts for SMP systems
# WARNING: on single-CPU systems, irqbalabce has no effect and exits immediately,
#          so it's probably best to supervise it only on multi-CPU systems!
exec 2>&1

NAME=irqbalance
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

exec "$DAEMON" --foreground
