#!/bin/sh
# pNFS block layout mapping daemon
# (cloux@rote.ch)
exec 2>&1

DAEMON=$(command -v blkmapd)
[ -x "$DAEMON" ] || exit

# Ensure that the RPC pipefs is available
if ! (mount | grep -q '^rpc_pipefs'); then
	printf "ERROR: blkmapd requires rpc_pipefs to be mounted.\n"
	exit 1
fi

exec "$DAEMON" -f
