#!/bin/sh
# NFSv4 kernel client and server ID <-> Name Mapper
#
# Activated automatically from rpcbind
# NOTE: on more recent kernels only the NFSv4 server uses rpc.idmapd,
# the client uses nfsidmap instead, and only falls back to rpc.idmapd
# if there was a problem running the nfsidmap program.
#
# (cloux@rote.ch)
exec 2>&1

NAME=rpc.idmapd
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# Ensure that the RPC pipefs is available
if ! (mount | grep -q '^rpc_pipefs'); then
	printf "ERROR: rpc.idmapd requires rpc_pipefs to be mounted.\n"
	exit 1
fi

# Terminate unsupervised instance
pkill --exact "$NAME" 2>/dev/null

# Run daemon
exec "$DAEMON" -f
