#!/bin/sh
# Pure-ftpd server
# (cloux@rote.ch)
exec 2>&1

CONF_DIR=/etc/pure-ftpd/conf
[ -d "$CONF_DIR" ] || exit 0
DAEMON="$(command -v pure-ftpd-wrapper)"
[ -x "$DAEMON" ] || exit 0
[ -r /etc/default/pure-ftpd-common ] && . /etc/default/pure-ftpd-common

# get authentication suffix: ldap/mysql/postgresql
SUFFIX=
PGCONF=$($DAEMON --show-options 2>/dev/null)
if (printf "%s" "$PGCONF" | grep -q ldap); then
	SUFFIX="ldap"
elif (printf "%s" "$PGCONF" | grep -q mysql); then
	SUFFIX="mysql"
elif (printf "%s" "$PGCONF" | grep -q pgsql); then
	SUFFIX="postgresql"
fi

# always use real external IP for passive mode
PUBLIC_IP="$(curl http://checkip.amazonaws.com 2>/dev/null)"
[ "$PUBLIC_IP" ] && printf "%s\n" "$PUBLIC_IP" > $CONF_DIR/ForcePassiveIP

echo "No" > $CONF_DIR/Daemonize
exec $DAEMON $SUFFIX
