#!/bin/sh
# Pure-ftpd server
# (cloux@rote.ch)
exec 2>&1

CONF_DIR=/etc/pure-ftpd/conf
[ -d "$CONF_DIR" ] || exit
DAEMON="$(command -v pure-ftpd-wrapper)"
[ -x "$DAEMON" ] || exit
[ -r /etc/default/pure-ftpd-common ] && . /etc/default/pure-ftpd-common

# use valid external IP for passive mode
PUBLIC_IP=$(public-ip 2>/dev/null)
if printf "%s" "$PUBLIC_IP" | grep -iq '[a-z]'; then
	# use external IP, if at least one of the DOMAINS in /etc/default/public-domain
	# resolve to our external IP
	PUBLIC_IP="$(printf "%s" "$PUBLIC_IP" | grep -o '^[0-9.]*')"
else
	# otherwise use first interface IP (hopefully this would be the LAN IP)
	PUBLIC_IP="$(hostname -I 2>/dev/null | head -n 1 | grep -o '^[0-9.]*')"
fi
[ "$PUBLIC_IP" ] && printf "%s\n" "$PUBLIC_IP" > $CONF_DIR/ForcePassiveIP

# get authentication suffix: ldap/mysql/postgresql
SUFFIX=
PGCONF=$($DAEMON --show-options 2>/dev/null)
if (printf "%s" "$PGCONF" | grep -q ldap); then
	SUFFIX="ldap"
elif (printf "%s" "$PGCONF" | grep -q mysql); then
	SUFFIX="mysql"
elif (printf "%s" "$PGCONF" | grep -q pgsql); then
	SUFFIX="postgresql"
fi

printf "No\n" > $CONF_DIR/Daemonize
exec $DAEMON $SUFFIX
