#!/bin/sh
# Wicd Network Manager
# (cloux@rote.ch)
exec 2>&1

NAME=wicd
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# Load config
DAEMON_ARGS="--keep-connection"
[ -r /etc/default/$NAME ] && . /etc/default/$NAME
[ -r ./conf ] && . ./conf
[ "$START_DAEMON" = "no" ] && exit

# Wait for DBus
sv start dbus >/dev/null || exit

rm -f /run/wicd/wicd.pid
exec "$DAEMON" --no-daemon $DAEMON_ARGS >/dev/null 2>/dev/null
