#!/bin/sh
# 
# AWS EC2 cloud-init, see /etc/init.d/cloud-init
# This is started parallel in the background (nohup) by 20-parallel.sh
# (cloux@rote.ch)

# AWS EC2 cloud-init, see /var/log/cloud-init.log
[ -x "/usr/bin/cloud-init" ] || exit

export PATH=/usr/sbin:/usr/bin:/sbin:/bin

# clean up
rm -f /var/log/cloud-init.log /var/log/cloud-init-output.log

# load config
[ -r /etc/default/cloud-init ] && . /etc/default/cloud-init

# init
/usr/bin/cloud-init init
/usr/bin/cloud-init init --local
/usr/bin/cloud-init modules --mode config
/usr/bin/cloud-init modules --mode final
