#!/bin/sh
#
# Start firewall
# (cloux@rote.ch)

[ -x /usr/sbin/firehol ] || exit

([ -r /etc/default/firehol ] && set -a ) && . /etc/default/firehol
[ $(printf "%s" "$START_FIREHOL" | grep -ic 'no') -ne 0 ] && exit

# firehol requires iptables-legacy, see
# https://github.com/netblue30/firejail/issues/2232#issuecomment-436423748 
update-alternatives --set iptables /usr/sbin/iptables-legacy >/dev/null

/usr/sbin/firehol start
