#!/bin/sh
#
# Activate/deactivate SERVICES if my public IP
# matches the DOMAINS in /etc/default/public-domain
# (cloux@rote.ch)

# Run periodically, every DELAY seconds
DELAY=40

# echo date format
DATEFMT='%Y-%m-%d_%H:%M:%S.%N'

while true; do

	# load SERVICES to activate/deactivate, if DOMAINS resolve to me
	[ -s /etc/default/public-domain ] && . /etc/default/public-domain
	[ "$DOMAINS" -a "$SERVICES" ] || exit

	# check if one of the DOMAINS resolves to IP address of this server
	PUBLIC_IP=$(public-ip 2>/dev/null)
	[ $? -eq 0 ] || exit
	if [ "$PUBLIC_IP" -a "$PUBLIC_IP" != "$(cat /var/run/public-ip 2>/dev/null)" ]; then
		echo -n "$PUBLIC_IP" >/var/run/public-ip
		echo -n "$(date +$DATEFMT): Public IP changed to $PUBLIC_IP,"
		if [ $(echo "$PUBLIC_IP" | grep -c '[a-z]') -eq 0 ]; then
			echo " no assigned domain, deactivating services"
			svdeactivate $SERVICES 2>&1
		else
			echo " activating services"
			svactivate $SERVICES 2>&1
		fi
		echo "$(date +$DATEFMT): DONE"
	fi

	# cycle with delay
	sleep $DELAY

done
