#!/bin/sh
# Start Wicd Network Manager
# NOTE: doesn't support foreground mode, so it cannot run supervised 
# (cloux@rote.ch)
exec 2>&1

# NOTE: If PATH variable is missing, wicd daemon dies
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

NAME=wicd
DAEMON=$(command -v $NAME)
if [ ! -x "$DAEMON" ]; then
	printf "ERROR: Wicd daemon not found.\n"
	exit
fi

# Config
RUNDIR=/var/run/$NAME
DAEMON_ARGS="--keep-connection"
[ -r /etc/default/$NAME ] && . /etc/default/$NAME
if [ "$START_DAEMON" = "no" ]; then
	printf "INFO: Daemon autorun disabled in /etc/default/wicd, exiting.\n"
	exit
fi

# Create RUNDIR if it doesn't exist
[ -d "$RUNDIR" ] || mkdir -p "$RUNDIR"

# Wait for DBus
while ! sv check dbus >/dev/null 2>/dev/null; do
	printf "Waiting for DBus...\n"
	sleep 0.2
done

# Clean PID file
rm -f "$RUNDIR/wicd.pid"

# Run 
printf "Starting wicd ... "
"$DAEMON" $DAEMON_ARGS >/dev/null 2>/dev/null
sleep 0.2
if [ -s "$RUNDIR/wicd.pid" ]; then
	printf "OK\n"
else
	printf "FAILED\n"
fi
