#!/bin/sh -eu
# PostgreSQL Cluster
# see 'man pg_ctlcluster' and 'man pg_ctl' for details
#
# (cloux@rote.ch)

DAEMON="$(which pg_ctlcluster)"
[ -x "$DAEMON"] || exit 1

PGBINROOT="/usr/lib/postgresql/"
[ -r ./config ] && . ./config
[ -d "$PGBINROOT" ] || exit 1

OPTIONS=
VERSION=
NAME=
[ -z "$VERSION" ] && VERSION=$(ls -1v $PGBINROOT | tail -n 1)
[ -z "$NAME" ] && NAME=$(ls -1tr /etc/postgresql/$VERSION | tail -n 1)

install -d -m 2775 -o postgres -g postgres -d /run/postgresql
exec chpst -u postgres $DAEMON --foreground --skip-systemctl-redirect $VERSION $NAME start -- $OPTIONS
