#!/bin/sh
# MySQL/MariaDB server
exec 2>&1

DAEMON="$(command -v mysqld)"
[ -x "$DAEMON" ] || exit

[ -f /etc/default/mysql ] && . /etc/default/mysql
[ -f /etc/default/mariadb ] && . /etc/default/mariadb
[ -e /var/run/mysqld ] || install -m 755 -o mysql -g root -d /var/run/mysqld

export HOME=/etc/mysql
if [ ! -r "$HOME/my.cnf" ]; then
	printf "ERROR: %s/my.cnf cannot be read." "$HOME"
	exit 1
fi

DATADIR=$(grep '^datadir' "$HOME/my.cnf" | sed 's/.*=\s*//')
if [ ! -d "$DATADIR" ]; then
	printf "ERROR: datadir in %s/my.cnf is not a directory." "$HOME"
	exit 1
fi

# ensure sysvinit compatibility - replace init.d script with symlink to sv
NAME=${PWD##*/}
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

exec chpst -u mysql "$DAEMON"
