#!/bin/sh
# Enable user and session management by elogind
# (cloux@rote.ch)
exec 2>&1

NAME=${PWD##*/}
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

sv start dbus >/dev/null || exit
sv check dbus >/dev/null || exit

# run daemon, keep quiet about found buttons etc.
exec "$DAEMON" >/dev/null 2>/dev/null
