#!/bin/sh
# Start NTP daemon
exec 2>&1

DAEMON=$(command -v ntpd)
[ -x "$DAEMON" ] || exit

[ -r /etc/default/ntp ] && . /etc/default/ntp
[ -e /run/ntp.conf.dhcp ] && NTPD_OPTS="$NTPD_OPTS -c /run/ntp.conf.dhcp"
NTPD_OPTS="$NTPD_OPTS -n -u ntp:ntp"

# ensure sysvinit compatibility - replace init.d script with symlink to sv
NAME=${PWD##*/}
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

exec $DAEMON $NTPD_OPTS
