#!/bin/sh -e
exec 2>&1
service=${PWD##*/}

sv start eudev || exit 1

# enable triggers for eudev
/sbin/udevadm trigger --type=subsystems --action=add
/sbin/udevadm trigger --type=devices --action=add
/sbin/udevadm settle  --timeout=5

sv shutdown $service
