#!/bin/sh
#
# AWS EC2 instance - cleanup for redistribution
#
# WARNING: BIOHAZARD!!!
# The instance will become unaccessible after this!
# Run only before creating AMI for distribution.
#
# maybe this could be replaced by bootstrap-vz:
# https://github.com/andsens/bootstrap-vz
# http://bootstrap-vz.readthedocs.io
#

# Make sure that I'm root
if [ $(id -u) -ne 0 ]; then
	 echo "$0 - This script must be run as root!"
	 exit 1
fi

if [ "$1" != "force" ]; then
	echo "WARNING:"
	echo "Do not proceed, if not absolutely sure, that an AMI"
	echo "exported from this instance will start properly!!!"
	echo
	echo "This will remove all history, logs, and SSH keys!"
	echo "Instance will shutdown, can be exported as AMI and"
	echo "terminated afterwards."
	echo
	echo "To proceed, run this with 'force' parameter."
	exit
fi

# delete history
echo "Deleting history..."
rm -f /root/.bash_history 2>/dev/null
find /home -maxdepth 2 -type f -iname .bash_history -delete
find /home -type f -iname history -delete

# Delete all SSH keys. New will be generated by cloud-init when spawning
# a new instance from AMI.
echo "Deleting SSH keys..."
rm -f /etc/ssh/ssh_host_* 2>/dev/null
rm -f /root/.ssh/*
find /home -type f -iname authorized_keys -delete

# stop log-creating services before deleting logfiles
echo "Stopping services..."
sv stop bootlogd cron hiawatha ntp socklog-unix

echo "Deleting logfiles..."
rm -f /var/log/boot.log* /var/log/cloud-init*.log /var/log/dmesg.log* \
   /var/log/apt/history.log* /var/log/apt/term.log* /var/log/hiawatha/* \
   /var/log/autorun*.log* 2>/dev/null
find /var/log -type f -iname current -delete
find /var/log -type f -iname '@*' -delete
find /var/log -type f -iname '*.gz' -delete
find /var/log -type f -iname '*.xz' -delete

# shut down instance
echo ""
echo "After shutdown, instance can be exported as AMI."
#sleep 3
#shutdown
