#!/bin/sh
#
# Show external IP and domains pointing to it
# (cloux@rote.ch)

# WARNING: on AWS, http://instance-data/latest/meta-data/public-ipv4 
#          will not reflect IP changes until instance restart!
#          Query external server for the real external IP, it's slower but reliable.
PUBLIC_IP=$(curl --max-time 5 -s http://checkip.amazonaws.com)
[ "$PUBLIC_IP" ] || PUBLIC_IP=$(curl --max-time 5 -s http://ipecho.net/plain)
#[ "$PUBLIC_IP" ] || PUBLIC_IP=$(curl --max-time 5 -s https://api.ipify.org)
printf "%s" "$PUBLIC_IP"

# check if some of the DOMAINS point to me
if [ "$PUBLIC_IP" ] && [ -r /etc/default/public-domain ]; then
	# load DOMAINS as space separated list of domains to check
	. /etc/default/public-domain
	# show domain names that point to my public IP
	for DOMAIN_NAME in $DOMAINS; do
		DOMAIN_IP=$(dig +short "$DOMAIN_NAME" 2>/dev/null)
		[ "$PUBLIC_IP" = "$DOMAIN_IP" ] && printf " %s" "$DOMAIN_NAME"
	done
fi
printf "\n"
