#!/bin/sh
#
# Show external IP and domains pointing to it
# (cloux@rote.ch)

# load DOMAINS as space separated list of domains to check
[ -r /etc/default/public-domain ] && . /etc/default/public-domain

# On Amazon EC2, ask the instance-data
PUBLIC_IP="$(wget -qO- http://instance-data/latest/meta-data/public-ipv4 2>/dev/null)"
# if that fails, ask the external service
[ -z "$PUBLIC_IP" ] && PUBLIC_IP=$(wget -qO- http://ipecho.net/plain 2>/dev/null | grep -o '[0-9.]*')
echo -n $PUBLIC_IP

# show domain names that point to the public IP
for DOMAIN_NAME in $DOMAINS; do
	DOMAIN_IP=$(dig +short "$DOMAIN_NAME" 2>/dev/null)
	[ "$PUBLIC_IP" = "$DOMAIN_IP" ] && echo -n " $DOMAIN_NAME"
done
echo
