#!/bin/sh
# Reload the OpenSSH server when an interface comes up, to allow it to start
# listening on new addresses.

# Don't bother to restart sshd when lo is configured.
[ "$IFACE" = lo ] && exit

# Only run from ifup.
[ "$MODE" = start ] || exit

# OpenSSH only cares about inet and inet6. Get ye gone, strange people
# still using ipx.
([ "$ADDRFAM" != inet ] && [ "$ADDRFAM" != inet6 ]) && exit

# Is /usr mounted?
[ -e /usr/sbin/sshd ] || exit

if [ "$(pgrep runsvdir)" ] && [ -f /etc/service/ssh ]; then
  sv restart ssh >/dev/null 2>/dev/null
elif [ ! -f /etc/service/ssh ]; then
  ([ ! -f /run/sshd.pid ] || [ "$(ps -p "$(cat /run/sshd.pid)" -o comm=)" != sshd ]) && exit
  # We'd like to use 'reload' here, but it has some problems; see #502444.
  invoke-rc.d ssh restart >/dev/null 2>/dev/null || true
fi
