#!/bin/sh
# LVM metadata cache daemon
# (cloux@rote.ch)
exec 2>&1

NAME=lvmetad
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# stop any unsupervised daemons
killall --quiet --exact "$NAME"

exec "$DAEMON" -f
