#!/bin/sh
# System-wide dbus
exec 2>&1

DAEMON=$(command -v dbus-daemon)
[ -x "$DAEMON" ] || exit

[ ! -d /run/dbus ] && install -m755 -d /run/dbus

# Create machine ID file
UUIDGEN=$(command -v dbus-uuidgen)
[ -x "$UUIDGEN" ] && "$UUIDGEN" --ensure

exec "$DAEMON" --system --nofork --nopidfile --nosyslog
