#!/bin/sh
# DHCP and BOOTP IPv4+IPv6 Client
# (cloux@rote.ch)
exec 2>&1

NAME=dhcpcd
DAEMON=$(command -v "$NAME")
[ -x "$DAEMON" ] || exit

# stop daemon running outside of runsvdir
"$DAEMON" --exit 2>/dev/null
killall --quiet --exact "$NAME"

exec "$DAEMON" --nobackground --master --lastlease --quiet 2>/dev/null
