#!/bin/sh
# DHCP and BOOTP IPv4+IPv6 Client
# (cloux@rote.ch)
exec 2>&1

NAME=${PWD##*/}
DAEMON=$(command -v "$NAME")
[ -x "$DAEMON" ] || exit

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

# stop daemon running outside of runsvdir
"$DAEMON" --exit 2>/dev/null
killall --quiet --exact "$NAME"

exec "$DAEMON" --nobackground --master --lastlease --quiet 2>/dev/null
